apiVersion: v1
kind: Pod
metadata: 
  labels: 
    run: busybox3
  name: mywawitobusypod
  namespace: wawito
spec: 
  containers: 
    - 
      command: 
        - /bin/sh
        - "-c"
        - |
            echo "running below scripts"
            i=0; 
            while true; 
            do 
              echo "THEEEEEEEEEEE $i: $(date)"; 
              i=$((i+1)); 
              sleep 1; 
            done
      image: busybox
      name: mywawitobusypod
